### ISSUE TITLE
Bug: Cmd+Click on the link opens it twice (in both current tab & new tab)

### ISSUE THREAD

**Issue by NovaDev94** [AdeelH/find-on-reddit#20] opened 2021-01-20 12:15 UTC

**Comment by AdeelH** [comment] 2021-01-20 13:13
Thanks for the report. I am able to reproduce it. I don't recall experiencing it before, so it's possible it's due to some change in newer versions of Chrome. I'll attempt to fix this this weekend.

As a workaround, I would suggest turning on these 2 options:
![image](https://user-images.githubusercontent.com/13014700/105179107-b2c69b80-5b4a-11eb-9416-c460fd339c99.png)

This is what I personally use. It allows you to open as many threads as you like (with a simple click) without exiting the popup.

**Comment by AdeelH** [comment] 2021-01-24 07:54
The fix has been published and will become available through the webstore as soon as it has passed review.

**Comment by NovaDev94** [comment] 2021-01-25 17:54
Thank you for the fix, @AdeelH. But seem like the bug is still there (I'm at v1.5.1)

https://user-images.githubusercontent.com/6073918/105745585-04b75900-5f71-11eb-8461-12383518c475.mp4

**Comment by AdeelH** [comment] 2021-01-25 18:16
Ah, it seems like I only fixed it for ctrl+click, but it should be possible to handle cmd+click in the same way. I do not currently have access to a Mac to test this with, so if you are able to, can you try the following and see if it fixes it:

- disable the webstore version of the extension
- clone the repo
- go to 'manage extensions' and load the extension from source using 'load unpacked extension'
- modify this line https://github.com/AdeelH/find-on-reddit/blob/7096fd06a2de8c862224a6a0bbe146746fc306c4/popup.js#L51
- to `if (e.ctrlKey || e.metaKey) { `

**Comment by NovaDev94** [comment] 2021-01-25 21:06
That fix works for me! Thank you!

**Comment by AdeelH** [comment] 2021-01-26 04:26
Fantastic! I have extended this fix to include cmd, shift, and alt keys too. The webstore version should update in a while.

This was a very good catch. Thank you so much!

**Closed by AdeelH** 2021-01-26 04:26 UTC
Labels: bug
